services:
- type: web
  name: oj-backend
  env: python
  pythonVersion: 3.11
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
  autoDeploy: true
  envVars:
    - key: DATABASE_URL
      sync: false
    - key: JUDGE0_URL
      value: https://ce.judge0.com
